// addSbtPlugin("net.virtual-void" % "sbt-dependency-graph"     % "0.9.0")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "1.0.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.3.9")
addSbtPlugin("com.tapad"         % "sbt-docker-compose"  % "1.0.35")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.8.2")
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger"      % "2.0.0-RC24")
addDependencyTreePlugin
