apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-deployment
  labels:
    app: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
      - name: mc
        image: minio/mc
        ports:
        - containerPort: 80